sudo: required

language: c++

services:
  - docker

before_install:
- docker build . -t lifx-device/test

script:
- docker run -v $TRAVIS_BUILD_DIR:/lifx lifx-device/test /bin/sh -c "set -e; cd /lifx/; cmake CMakeLists.txt; make; ./runTests"


